// Code generated by protoc-gen-gogo.
// source: internal/congo.proto
// DO NOT EDIT!

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	internal/congo.proto

It has these top-level messages:
	User
*/
package internal

import proto "github.com/gogo/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type User struct {
	ID               *uint64 `protobuf:"varint,1,req" json:"ID,omitempty"`
	FirstName        *string `protobuf:"bytes,2,req" json:"FirstName,omitempty"`
	LastName         *string `protobuf:"bytes,3,req" json:"LastName,omitempty"`
	Email            *string `protobuf:"bytes,4,req" json:"Email,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}

func (m *User) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil && m.FirstName != nil {
		return *m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil && m.LastName != nil {
		return *m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func init() {
}
